//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutas
    {
        public System.Guid IdRuta { get; set; }
        public string Chofer { get; set; }
        public string Compania { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual Localizacion Estaciones { get; set; }
    }
}
